### ISSUE TITLE
is it possible to update VLC to newer version?

### ISSUE THREAD

**Issue by masterchop** [galexrt/docker-vlc#2]
I tried a new release but didnt work. Do you know how to?

**Comment by galexrt** [comment]
What error did you get when running the image? Which command did you use to run the image?

I can look into updating the image in the next few days.

**Comment by masterchop** [comment]
it seems it only happen if do ubuntu:latest but 16.04 and 18.04 worked like a charm so that is good enough for me.

Thanks

**Comment by galexrt** [comment]
I have pushed the tag `v20201206-021245-115`, which is currently being built, that tag should have a more uptodate VLC version as the OS used now is Fedora 33 (`fedora:33`).

**Comment by masterchop** [comment]
do you happen to know why doesnt work if i deploy through jenkins? but terminal works just fine?

**Comment by galexrt** [comment]
You need to make sure that your Jenkins is using the latest source code of the repo.
Jenkins then just needs to build the container image using the `Dockerfile` and it should be good to go.
